activate nvm

diff --git a/.github/workflows/deploy-to-next.yml b/.github/workflows/deploy-to-next.yml
--- a/.github/workflows/deploy-to-next.yml
+++ b/.github/workflows/deploy-to-next.yml
@@ -18,6 +18,14 @@ jobs:
           key: ${{ secrets.KEY }}
           script_stop: true
           script: |
+            export NVM_DIR="$HOME/.nvm"
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              . "$NVM_DIR/nvm.sh"
+              echo "NVM loaded successfully."
+            else
+              echo "Error: NVM not found at $NVM_DIR"
+              exit 1
+            fi
             cd /opt/next_web/packages/react || { echo "No directory found"; exit 1; } 
             nvm use
             git pull origin next
